matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 3.0.100
      before_script:
        - cd NTDOY/NTDOY_Microservice
      script:
        - dotnet publish && dotnet test
      after_script:
        - cd ../..

    - language: python
      python:
        - 3.7

    - language: node_js
      node_js: node

#before_install:
#  - nvm install node
#  - pyenv install 3.7.0a1

install:
  - npm install
  - pip install -r requirements.txt

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: #unit test command here, but will it run right?
    - script: #integration test command here
      name: "Integration Tests"
