language: csharp
mono: none
dotnet: 3.0.100
script:
  - cd NTDOY_Microservice && dotnet restore && cd ..

before_install:
  - nvm install node
  - pyenv install

install:
  - npm install
  - pip install -r requirements.txt

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: #unit test command here
    - script: #integration test command here
      name: "Integration Tests"
