language: python
python:
  - "3.7"

cache:
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - stage: build
      script:
        - npm i
        - npm run build
    - stage: test
      script: pytest main_test.py
    -
      script: pytest new_tests.py
    - #cypress headless tests
      before_script:
        - npm i
        - chmod +x ./start_server.sh
        - ./start_server.sh
      script:
        - ./node_modules/.bin/cypress run
    - stage: lint
      script: pylint -E main.py
    - stage: deploy
      script: skip     # usually you do not want to rerun any tests
      deploy: &gae
        provider: gae
        project: obsmainservice
        skip_cleanup: true
