language: python
python:
  - "3.7"

#addons:
#  sonarcloud:
#    organization: "team-6-obs"
#    token:
#      secure: SONAR_TOKEN

jobs:
  include:
    - stage: build
      script: pip install -r requirements.txt
    - #install node dependencies and try to use webpack to build javascript
      script:
        - npm install
        - npm run build
    - stage: test
      script: pytest micro/adam
    #-
      #script: pytest micro/michael
    #-
      #script: pytest micro/sean
    -
      script: pytest micro/ben
    #-
      script: pytest micro/carlos
    - stage: lint
      script:
        - pylint micro/adam/main.py
        - pylint micro/michael/main.py
        #- pylint micro/sean/main.py
        - pylint micro/ben/main.py
        - pylint micro/carlos/main.py
        - pylint main.py
#    - stage: static analysis
#      script: sonar-scanner



#before_install:
#  - nvm install node
#  - pyenv install 3.7.0a1

#install:
#  - npm install
#  - pip install -r requirements.txt
