env:
  - SECRET=XCAP05H6LoKvbRRa/QkqLNMI7cOHguaRyHzyg7n5qEkGjQmtBhz4SzYh4Fqwjyi3KJHlSXKPwVu2+bXr6CtpgQ==
  - TRADIER_BEARER=uhzCQ8Lzm5Tx35faBndmsYmQgE4d

jobs:
  include:
    - stage: build
      matrix:
        include:
          - language: python
            python: 3.7
            script:
              - pip install -r requirements.txt
              - pylint main.py
          - language: node_js
            node_js: node
            script:
              - npm install
    - stage: test
      script: cd micro/adam && pytest && cd ../..




#before_install:
#  - nvm install node
#  - pyenv install 3.7.0a1

#install:
#  - npm install
#  - pip install -r requirements.txt
