matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.1.300
      before_script:
        - cd NTDOY/NTDOY_Microservice
      script:
        - dotnet publish
        - cd ../NTDOY.Test
        - dotnet test
      after_script:
        - cd ../..

    - language: python
      python: 3.7
      script:
        - pip install -r requirements.txt

    - language: node_js
      node_js: node
      script:
        - npm install

#before_install:
#  - nvm install node
#  - pyenv install 3.7.0a1

#install:
#  - npm install
#  - pip install -r requirements.txt
