language: python
python:
  - "3.7"

env:
  - SECRET=XCAP05H6LoKvbRRa/QkqLNMI7cOHguaRyHzyg7n5qEkGjQmtBhz4SzYh4Fqwjyi3KJHlSXKPwVu2+bXr6CtpgQ==
  - TRADIER_BEARER=uhzCQ8Lzm5Tx35faBndmsYmQgE4d

matrix:
  include:
    - language: python
      python: 3.7
      script:
        - pip install -r requirements.txt
        - pylint main.py
        - cd micro/adam && pytest && cd ../..
    - language: node_js
      node_js: node
      script:
        - npm install
        - npm run build




#before_install:
#  - nvm install node
#  - pyenv install 3.7.0a1

#install:
#  - npm install
#  - pip install -r requirements.txt
