language: csharp
mono: none
dotnet: 3.0.100
script:
  - cd NTDOY/NTDOY_Microservice && dotnet publish && dotnet test && cd ../..

before_install:
  - nvm install node
  - pyenv install 3.7.0a1

install:
  - npm install
  - sudo pip install -r requirements.txt

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: #unit test command here
    - script: #integration test command here
      name: "Integration Tests"
